[package]
name = "click"
version = "0.1.0"
authors = ["Philip Dumaresq <phdumaresq@gmail.com>"]
edition = "2018"
description = ""
default-run = "click-vm"

[[bin]]
name = "click-vm"
path = "src/vm/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
